config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  resources :adaptations, except: [:new, :create]
  resources :books do
    resources :adaptations, only: [:new, :create]
  end

  resources :users
  resource :session

end

app/models/adaptation.rb
class Adaptation < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :adaptations, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  has_many :adaptations
end

app/controllers/adaptations_controller.rb
class AdaptationsController < ApplicationController

  def index
    @adaptations = Adaptation.all
  end

  def show
    @adaptation = Adaptation.find(params[:id])
  end

  def new
    redirect_to root_path unless @current_user
    @book = Book.find(params[:book_id])
    @adaptation = @book.adaptations.new
  end

  def create
    redirect_to root_path unless @current_user
    @book = Book.find(params[:book_id])
    @adaptation = @book.adaptations.new(adaptation_params)
    @adaptation.user = @current_user
    @adaptation.save
    redirect_to @adaptation
  end

  def edit
    redirect_to root_path unless @current_user
    @adaptation = Adaptation.find(params[:id])
  end

  def update
    redirect_to root_path unless @current_user
    @adaptation = Adaptation.find(params[:id])
    @adaptation.update(adaptation_params)
    redirect_to adaptation_path
  end

  def destroy
    redirect_to root_path unless @current_user
    @adaptation = Adaptation.find(params[:id])
    @adaptation.destroy
    redirect_to adaptations_path
  end

  private
  def adaptation_params
    params.require(:adaptation).permit(:title, :date_of_release, :image_url, :comparison_to_book, :book_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :get_current_user

  def get_current_user
    if User.exists?(session[:user_id])
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    redirect_to root_path unless @current_user
    @book = Book.new
  end

  def create
    redirect_to root_path unless @current_user
    @book = @current_user.books.create!(book_params)
    redirect_to books_path
  end

  def edit
    redirect_to root_path unless @current_user
    @book = Book.find(params[:id])
  end

  def update
    redirect_to root_path unless @current_user
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to book_path
  end

  def destroy
    redirect_to root_path unless @current_user
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :date_of_publication, :image_url, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    input_username = params[:user][:username]
    if User.exists?(username: input_username)
      @user = User.find_by(username: input_username)
      if @user.password === params[:user][:password]
        flash[:notice] = "You're signed in!"
        session[:user_id] = @user.id
        redirect_to root_path
      else
        flash[:alert] = "Wrong password!"
        redirect_to new_session_path
      end
    else
      flash[:alert] = "That user doesn't exist!"
      redirect_to new_session_path
    end
  end

  def destroy
    reset_session
    flash[:notice] = "You're signed out!"
    redirect_to :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    redirect_to root_url unless @current_user == @user
  end

  def update
    @user = User.find(params[:id])
    redirect_to root_url unless @current_user == @user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @books = Book.order("RANDOM()").limit(3)
    # Didn't know you could do this!
    @adaptations = Adaptation.order("RANDOM()").limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adaptations/edit.html.erb
<div class="move_down">
  <h2>Edit Adaptation</h2>

  <div class="row">
    <div class="col-xs-12">

      <%= form_for [@book, @adaptation], :html => {:class => "form-horizontal center"} do |f| %>
      <fieldset>

        <div class="form-group">
          <%= f.label :title, "Title:", class: "col-xs-4 control-label white-text" %>
          <div class="col-xs-6">
            <%= f.text_field :title, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :date_of_release, "Date of Publication:", class: "col-xs-4 control-label white-text" %>
          <div class="col-xs-6">
            <%= f.text_field :date_of_release, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :comparison_to_book, "Comparison to Book:", class: "col-xs-4 control-label white-text" %>
          <div class="col-xs-6">
            <%= f.select :comparison_to_book, [["..why did they think this was a good idea"], ["it didn't do the book justice"], ["not good but not bad either"], ["it was good"], ["THIS...IS...AWESOME!!!!!"]], class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :image_url, "Image URL:", class: "col-xs-4 control-label white-text" %>
          <div class="col-xs-6">
            <%= f.text_field :image_url, class: "form-control" %>
          </div>
        </div>

        <div class="form-actions">
          <%= f.submit "Submit", class: "btn btn-default btn-primary pull-right move_left" %>
        </div>
      </fieldset>
      <% end %>
    </div>
  </div>

  <%= form_for @adaptation, method: :delete do |f| %>
  <%= f.submit "Delete adaptation", class: "delete btn btn-danger pull-right move_left" %>
  <% end %>

</div>

app/views/adaptations/index.html.erb
<div class="move_down">

  <div class="col-xs-6">
    <h2 class="move_up">The Adaptations</h2>
  </div>

<div class="row move_down_more"> <!-- <sarcasm>Great non-semantic name for a CSS class!</sarcasm> -->

  <div class="col-xs-8 col-centered text-center">
    <table class="table">
      <% @adaptations.each do |adaptation| %>
      <tr>
        <td>
          <%= link_to "#{adaptation.title} (#{adaptation.date_of_release})", adaptation_path( adaptation ) %>
        </td>
        <% end %>
      </tr>
    </table>
  </div>
</div>
</div>

app/views/adaptations/new.html.erb
<div class="move_down">
<h2>Add New Adaptation</h2>

<div class="row">
  <div class="col-xs-12">

<%= form_for [@book, @adaptation], :html => {:class => "form-horizontal center"} do |f| %>
<fieldset>
<!-- Since your forms are so similar, it wouldn't be a bad idea to put this form in a reusable partial view. -->
     <div class="form-group">
       <%= f.label :title, "Title:", class: "col-xs-4 control-label white-text" %>
       <div class="col-xs-6">
         <%= f.text_field :title, class: "form-control" %>
       </div>
     </div>

     <%= f.hidden_field :book_id, :value => @book.id %>
     <!-- If you're using nested routes, this isn't necessary. In your controller, use:

     @book = Book.find(params[:book_id])
     @book.adaptations.create(adaptation_params)

     It'll figure out the book ID for you, and is much more secure than relying on something in your HTML which any user could change using "inspect element"-->

     <div class="form-group">
       <%= f.label :date_of_release, "Date of Publication:", class: "col-xs-4 control-label white-text" %>
       <div class="col-xs-6">
         <%= f.text_field :date_of_release, class: "form-control" %>
         <!-- Take a look at Rails' date fields for forms -->
       </div>
     </div>

     <div class="form-group">
       <%= f.label :comparison_to_book, "Comparison to Book:", class: "col-xs-4 control-label white-text" %>
       <div class="col-xs-6">
           <%= f.select :comparison_to_book, [["..why did they think this was a good idea"], ["it didn't do the book justice"], ["not good but not bad either"], ["it was good"], ["THIS...IS...AWESOME!!!!!"]], class: "form-control" %>
       </div>
     </div>

     <div class="form-group">
       <%= f.label :image_url, "Image URL:", class: "col-xs-4 control-label white-text" %>
       <div class="col-xs-6">
         <%= f.text_field :image_url, class: "form-control" %>
       </div>
     </div>

     <div class="form-actions">
     <%= f.submit "Submit", class: "btn btn-default btn-primary pull-right move_left" %>
   </div>
 </fieldset>
 <% end %>
</div>
</div>

app/views/adaptations/show.html.erb
<div class="move_down">
<!-- Everything inside this div should be indented. :( -->

<div class="col-xs-12 move_up">

  <div class="col-xs-4 pull-right">
    <!-- What's this guy doing? -->
  </div>

  <div class="col-xs-12">
    <h2> <%= @adaptation.title %>
      <p class="inline small white-text">
        <%= "(#{@adaptation.date_of_release})"%>
      </p>
      <p class="inline small yellow-text">
            <%= link_to("(edit adaptation)", edit_adaptation_path) if @current_user %>
          </p>
    </h2>
  </div>
</div>

<div class="row">

  <div class="col-xs-8 text-center move_down_more">
    <table class="table">
      <tr>
        <td>
          <p class="move_down_more white-text"> Comparison to Book:
            <%= @adaptation.comparison_to_book%>
          </p>
        </td>
      </tr>
      <tr>
        <td>
          <p class="move_down_more white-text"> Adapted from:
            <%= link_to @adaptation.book.title, book_path(@adaptation.book_id)%>
          </p>
        </td>
      </tr>
    </table>
  </div>
  <div class="col-xs-4 pull-right">
    <p><%= image_tag(@adaptation.image_url, class: "img-responsive shape", :alt => "it's a pic!")%></p>
  </div>

</div>
</div>

app/views/books/edit.html.erb
<div class="move_down">
  <h2>Edit Book</h2>

  <div class="row">
    <div class="col-xs-12">

      <%= form_for @book, :html => {:class => "form-horizontal center"} do |f| %>
      <fieldset>

        <div class="form-group">
          <%= f.label :title, "Title:", class: "col-xs-4 control-label white-text" %>
          <div class="col-xs-6">
            <%= f.text_field :title, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :author, "Author:", class: "col-xs-4 control-label white-text" %>
          <div class="col-xs-6">
            <%= f.text_field :author, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :date_of_publication, "Date of Publication:", class: "col-xs-4 control-label white-text" %>
          <div class="col-xs-6">
            <%= f.text_field :date_of_publication, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :description, "Description:", class: "col-xs-4 control-label white-text" %>
          <div class="col-xs-6">
            <%= f.text_field :description, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :image_url, "Image URL:", class: "col-xs-4 control-label white-text" %>
          <div class="col-xs-6">
            <%= f.text_field :image_url, class: "form-control" %>
          </div>
        </div>

        <div class="form-actions">
          <%= f.submit "Submit", class: "btn btn-default btn-primary pull-right move_left" %>
        </div>
      </fieldset>
      <% end %>
    </div>
  </div>

  <%= form_for @book, method: :delete do |f| %>
  <%= f.submit "Delete book", class: "delete btn btn-danger pull-right move_left" %>
  <% end %>

</div>

app/views/books/index.html.erb
<div class="move_down">

  <div class="col-xs-12 move_up">

      <h2>The Books
      <p class="inline small yellow-text"> <%= link_to("(add new book)", new_book_path) if @current_user %></p>
      </h2>


  </div>

  <div class="row move_down_more">

    <div class="col-xs-8 col-centered text-center">
      <table class="table">
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to "#{book.title} (#{book.author})", book_path(book) %>
          </td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>

</div>

app/views/books/new.html.erb
<div class="move_down">

<h2>Add New Book</h2>

<%= form_for @book, :html => {:class => "form-horizontal center"} do |f| %>
     <div class="form-group">
       <%= f.label :title, "Title:", class: "col-xs-4 control-label white-text" %>
       <div class="col-xs-6">
         <%= f.text_field :title, class: "form-control" %>
       </div>
     </div>

     <div class="form-group">
       <%= f.label :author, "Author:", class: "col-xs-4 control-label white-text" %>
       <div class="col-xs-6">
         <%= f.text_field :author, class: "form-control" %>
       </div>
     </div>

     <div class="form-group">
       <%= f.label :date_of_publication, "Date of Publication:", class: "col-xs-4 control-label white-text" %>
       <div class="col-xs-6">
         <%= f.text_field :date_of_publication, class: "form-control" %>
       </div>
     </div>

     <div class="form-group">
       <%= f.label :description, "Description:", class: "col-xs-4 control-label white-text" %>
       <div class="col-xs-6">
         <%= f.text_field :description, class: "form-control" %>
       </div>
     </div>

     <div class="form-group">
       <%= f.label :image_url, "Image URL:", class: "col-xs-4 control-label white-text" %>
       <div class="col-xs-6">
         <%= f.text_field :image_url, class: "form-control" %>
       </div>
     </div>

     <%= f.submit "Submit", class: "btn btn-default btn-primary pull-right move_left" %>
<% end %>

</div>

app/views/books/show.html.erb
<div class="move_down white-text">

  <div class="col-xs-12 move_up">

    <div class="col-xs-12">
      <h2> <%= @book.title %>
        <p class="inline small yellow-text">
          <%= link_to("(edit book)", edit_book_path) if @current_user %>
        </p>
      </h2>
    </div>
  </div>

  <div class="row">

    <div class="col-xs-8 text-center move_down_more">
      <table class="table">
        <tr>
          <td>
            <p class="move_down_more">
              <%= "#{@book.author}, #{@book.date_of_publication}" %>
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p class="move_down_more">
              <%= @book.description %>
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <h4 class="text-left">Adaptations</h4>
            <% @book.adaptations.each do |adaptation| %>
            <p class="text-left">
              <%= link_to adaptation.title, adaptation %>
            </p>
            <% end %>
            <p class="text-left">
              <%= link_to("(add new adaptation)", new_book_adaptation_path(@book)) if @current_user %>
            </p>
          </td>
        </tr>
      </table>
    </div>
    <div class="col-xs-4 pull-right">
      <p> <%= image_tag(@book.image_url, class: "img-responsive shape", :alt => "it's a pic!")%> </p>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Book2Adapt</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

<body>
  <div id="main-container" class="container">
    <div class="row">
      <div class="col-xs-6">
        <h1><%= link_to "Book2Adapt", root_path %></h1>
      </div>

      <div class="col-xs-6">
        <nav class="navbar navbar-default centered-pills" role="navigation">
          <ul class="nav nav-pills" role="tablist">
            <li class="highlight">
              <%= link_to "Books", books_path %>
            </li>
            <li class="highlight">
              <%= link_to "Adaptations", adaptations_path %>
            </li>
          </ul>
          <ul class="nav nav-pills">
            <% if @current_user %>
            <li class="no-uppercase">
              <%= link_to "Welcome, #{@current_user.username}!", user_path(@current_user) %>
            </li>
            <li>
              <%= link_to "Sign Out", session_path, method: :delete %>
            </li>
            <% else %>
            <li>
              <%= link_to "Sign Up", new_user_path %>
            </li>
            <li>
              <%= link_to "Sign In", new_session_path %>
            </li>
            <% end %>

        </ul>
        </nav>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 text-center">
        <% flash.each do |type, message| %>
        <h4 class="<%= type %>"> <%= message %> </h4>
        <% end %>
      </div>
    </div>
    <div class="row">
      <%= yield %>
    </div>
    <div class="row row-centered">
      <div class="col-xs-8 footer  col-centered">
        <footer>
          <p>

            <a href="https://www.linkedin.com/in/tlangley"><%= image_tag("http://i.imgur.com/cCfmpGg.png", class: "img", :alt => "LinkedIn Logo")%></a>

             Made by <a href="https://tvlangley.github.io/"> Toni Langley</a>

            <a href="https://github.com/tvlangley/book2adapt"><%= image_tag("http://i.imgur.com/sfYYsCc.png", class: "img", :alt => "Github logo")%></a></p>
          </footer>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<div class="move_down">

  <h2>Edit Your Profile</h2>

  <div class="row">
    <div class="col-xs-12">

      <%= form_for @user, :html => {:class => "form-horizontal center"} do |f| %>
      <fieldset>

        <div class="form-group">
          <%= f.label :username, "Username:", class: "col-xs-4 control-label white-text" %>
          <div class="col-xs-6">
            <%= f.password_field :username, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :password, "Password:", class: "col-xs-4 control-label white-text" %>
          <div class="col-xs-6">
            <%= f.text_field :password, class: "form-control" %>
          </div>
        </div>

        <div class="form-actions">
          <%= f.submit "Submit", class: "btn btn-default btn-primary pull-right move_left" %>
        </div>
      </fieldset>
      <% end %>
    </div>
  </div>

</div>

app/views/users/new.html.erb
<div class="move_down">

<h2>Sign Up</h2>

<%= form_for @user, :html => {:class => "form-horizontal center"} do |f| %>
     <div class="form-group">
       <%= f.label :username, "Username:", class: "col-xs-4 control-label white-text" %>
       <div class="col-xs-6">
         <%= f.text_field :username, class: "form-control" %>
       </div>
     </div>

     <div class="form-group">
       <%= f.label :password, "Password:", class: "col-xs-4 control-label white-text" %>
       <div class="col-xs-6">
         <%= f.password_field :password, class: "form-control" %>
       </div>
     </div>

     <%= f.submit "Submit", class: "btn btn-default btn-primary pull-right move_left" %>
<% end %>

</div>

app/views/users/show.html.erb
<div class="move_down">

  <div class="col-xs-12">
    <h2><%= @user.username %>
      <p class="inline small yellow-text">
        <%= link_to("(edit)", edit_user_path(@user)) if @current_user == @user %></p></h2>
      </div>

      <div class="row  white-text">

        <h3 class="text-center">My Additions</h3>
        <div class="col-xs-10 text-center move_down_more">
          <table class="table move_right">
            <thead>
              <tr>
                <th>
                  <h4 class="text-left">Books</h4>
                </th>
                <th>
                  <h4 class="text-right">Adaptations</h4>
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <% @user.books.each do |book| %>
                  <p class="text-left">
                    <%= link_to "#{book.title} (#{book.author})", book_path(book) %>
                  </p>
                  <% end %>
                </td>
                <td>
                  <% @user.adaptations.each do |adaptation| %>
                  <p class="text-right">
                    <%= link_to "#{adaptation.title} (#{adaptation.date_of_release})", adaptation_path( adaptation ) %>
                  </p>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

app/views/welcome/index.html.erb
<div class="move_down">

<div class="col-xs-12">
  <h2>Welcome!</h2>
</div>

<div class="row">

  <div class="col-xs-6 move_down_more">
    <table class="table text-center">
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to "#{book.title} (#{book.date_of_publication})", book_path( book ) %>
        </td>
        <% end %>
      </tr>
    </table>
  </div>

  <div class="col-xs-6 move_down_more">
    <table class="table text-center">
      <% @adaptations.each do |adaptation| %>
      <tr>
        <td>
          <%= link_to "#{adaptation.title} (#{adaptation.date_of_release})", adaptation_path( adaptation ) %>
        </td>
        <% end %>
      </tr>
    </table>
  </div>

</div>
</div>